In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
# Load the data
df = pd.read_csv('DataWithLabel.csv')
df

,Unnamed: 0,Name,Time,Store,Comment,label,sentiment_score,polarity
0,0,macantonioc,25-06-2007,DigInfo,interesting,"['', 'shopping experience']",0.4019,positive
1,1,donkeyfly69,27-02-2008,DigInfo,not even seem convenient,"['', 'shopping experience']",0.0000,neutral
2,2,donkeyfly69,27-02-2008,DigInfo,not want pay use shopping cart read recipe,"['', 'technology', 'general', 'payment and che...",0.0191,neutral
3,3,donkeyfly69,27-02-2008,DigInfo,invade privacy way much just get grocery,"['', 'general']",0.0000,neutral
4,4,donkeyfly69,27-02-2008,DigInfo,not even deep,[''],0.0000,neutral
...,...,...,...,...,...,...,...,...
209573,223255,Mark H.,09-09-2020,Walmart,call refund tell would take day get money back,"['', 'price and value', 'payment and checkout']",0.0000,neutral
209574,223256,Mark H.,09-09-2020,Walmart,walmart,[''],0.0000,neutral
209575,223257,Lorna B.,09-09-2021,Walmart,improve site much improve,[''],0.7003,positive
209576,223258,Lorna B.,09-09-2021,Walmart,far too many grocery available store not avail...,"['', 'technology', 'general']",0.0000,neutral
209577,223259,NATISHA J.,09-09-2021,Walmart,place need walmart lead sell good merchandise ...,"['', 'shopping experience']",0.7506,positive

In [ ]:
#drop the column which year is 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017
df=df.drop(df[df['Time'].str[-4:]=='2007'].index)
df=df.drop(df[df['Time'].str[-4:]=='2008'].index)
df=df.drop(df[df['Time'].str[-4:]=='2009'].index)
df=df.drop(df[df['Time'].str[-4:]=='2010'].index)
df=df.drop(df[df['Time'].str[-4:]=='2011'].index)
df=df.drop(df[df['Time'].str[-4:]=='2012'].index)
df=df.drop(df[df['Time'].str[-4:]=='2013'].index)
df=df.drop(df[df['Time'].str[-4:]=='2014'].index)
df=df.drop(df[df['Time'].str[-4:]=='2015'].index)
df=df.drop(df[df['Time'].str[-4:]=='2016'].index)
df=df.drop(df[df['Time'].str[-4:]=='2017'].index)
df

,Unnamed: 0,Name,Time,Store,Comment,label,sentiment_score,polarity
569,587,Jenae K.,01-06-2018,Amazon Go,store awesome super cool concept definitley se...,"['', 'data integration', 'marketing and commun...",0.9136,positive
570,588,Jenae K.,01-06-2018,Amazon Go,scan app enter store grab whatever want shelf ...,"['', 'technology', 'payment and checkout']",0.0772,positive
571,589,Jenae K.,01-06-2018,Amazon Go,product shelf sensor know grab item,"['', 'technology']",0.0000,neutral
572,590,Jenae K.,01-06-2018,Amazon Go,crazy no cashier no line,"['', 'payment and checkout']",-0.7003,negative
573,591,Jenae K.,01-06-2018,Amazon Go,super simple course still worker ensure entran...,"['', 'technology', 'shopping experience', 'pay...",0.7579,positive
...,...,...,...,...,...,...,...,...
209573,223255,Mark H.,09-09-2020,Walmart,call refund tell would take day get money back,"['', 'price and value', 'payment and checkout']",0.0000,neutral
209574,223256,Mark H.,09-09-2020,Walmart,walmart,[''],0.0000,neutral
209575,223257,Lorna B.,09-09-2021,Walmart,improve site much improve,[''],0.7003,positive
209576,223258,Lorna B.,09-09-2021,Walmart,far too many grocery available store not avail...,"['', 'technology', 'general']",0.0000,neutral
209577,223259,NATISHA J.,09-09-2021,Walmart,place need walmart lead sell good merchandise ...,"['', 'shopping experience']",0.7506,positive

In [16]:
#count the comment of each year
#count number of records per year
df= df['Time'].groupby(df['Time'].str[-4:]).count()
df

Time
2018    48950
2019    20376
2020    26179
2021    36670
2022    26940
Name: Time, dtype: int64