In [5]:
import pandas as pd
# read data
df = pd.read_csv('Data_drop_year.csv')
df

,Name,Time,Store,Comment,Aspect,polarity,'data integration','marketing and communication','technology','payment and checkout','shopping experience','unemployment','product available and store design','price and value','general','privacy and security'
0,Jenae K.,2018-06-01,Amazon Go,store awesome super cool concept definitley se...,"["" 'data integration'"", "" 'marketing and commu...",positive,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Jenae K.,2018-06-01,Amazon Go,scan app enter store grab whatever want shelf ...,"["" 'technology'"", "" 'payment and checkout'""]",positive,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Jenae K.,2018-06-01,Amazon Go,product shelf sensor know grab item,"["" 'technology'""]",neutral,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Jenae K.,2018-06-01,Amazon Go,crazy no cashier no line,"["" 'payment and checkout'""]",negative,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Jenae K.,2018-06-01,Amazon Go,super simple course still worker ensure entran...,"["" 'technology'"", "" 'shopping experience'"", "" ...",positive,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87641,Melissa C.,2020-08-09,Walmart,time worth stop come unless,"["" 'price and value'""]",negative,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
87642,Mark H.,2020-09-09,Walmart,lose shipment twice row delay order two week s...,"["" 'technology'"", "" 'unemployment'""]",negative,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
87643,Mark H.,2020-09-09,Walmart,call refund tell would take day get money back,"["" 'price and value'"", "" 'payment and checkout'""]",neutral,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
87644,Lorna B.,2021-09-09,Walmart,far too many grocery available store not avail...,"["" 'technology'"", "" 'general'""]",neutral,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
87645,NATISHA J.,2021-09-09,Walmart,place need walmart lead sell good merchandise ...,"["" 'shopping experience'""]",positive,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [23]:
#df_data, contain first eight columns
df_data = df.iloc[:,0:7]
df_data

,Name,Time,Store,Comment,Aspect,polarity,'data integration'
0,Jenae K.,2018-06-01,Amazon Go,store awesome super cool concept definitley se...,"["" 'data integration'"", "" 'marketing and commu...",positive,1.0
1,Jenae K.,2018-06-01,Amazon Go,scan app enter store grab whatever want shelf ...,"["" 'technology'"", "" 'payment and checkout'""]",positive,0.0
2,Jenae K.,2018-06-01,Amazon Go,product shelf sensor know grab item,"["" 'technology'""]",neutral,0.0
3,Jenae K.,2018-06-01,Amazon Go,crazy no cashier no line,"["" 'payment and checkout'""]",negative,0.0
4,Jenae K.,2018-06-01,Amazon Go,super simple course still worker ensure entran...,"["" 'technology'"", "" 'shopping experience'"", "" ...",positive,0.0
...,...,...,...,...,...,...,...
87641,Melissa C.,2020-08-09,Walmart,time worth stop come unless,"["" 'price and value'""]",negative,0.0
87642,Mark H.,2020-09-09,Walmart,lose shipment twice row delay order two week s...,"["" 'technology'"", "" 'unemployment'""]",negative,0.0
87643,Mark H.,2020-09-09,Walmart,call refund tell would take day get money back,"["" 'price and value'"", "" 'payment and checkout'""]",neutral,0.0
87644,Lorna B.,2021-09-09,Walmart,far too many grocery available store not avail...,"["" 'technology'"", "" 'general'""]",neutral,0.0
87645,NATISHA J.,2021-09-09,Walmart,place need walmart lead sell good merchandise ...,"["" 'shopping experience'""]",positive,0.0

In [26]:
#rename of the last column
df_data.rename(columns={"'data integration'":'data integration'}, inplace=True)
df_data

,Name,Time,Store,Comment,Aspect,polarity,'data integration'
0,Jenae K.,2018-06-01,Amazon Go,store awesome super cool concept definitley se...,"["" 'data integration'"", "" 'marketing and commu...",positive,1.0
1,Jenae K.,2018-06-01,Amazon Go,scan app enter store grab whatever want shelf ...,"["" 'technology'"", "" 'payment and checkout'""]",positive,0.0
2,Jenae K.,2018-06-01,Amazon Go,product shelf sensor know grab item,"["" 'technology'""]",neutral,0.0
3,Jenae K.,2018-06-01,Amazon Go,crazy no cashier no line,"["" 'payment and checkout'""]",negative,0.0
4,Jenae K.,2018-06-01,Amazon Go,super simple course still worker ensure entran...,"["" 'technology'"", "" 'shopping experience'"", "" ...",positive,0.0
...,...,...,...,...,...,...,...
87641,Melissa C.,2020-08-09,Walmart,time worth stop come unless,"["" 'price and value'""]",negative,0.0
87642,Mark H.,2020-09-09,Walmart,lose shipment twice row delay order two week s...,"["" 'technology'"", "" 'unemployment'""]",negative,0.0
87643,Mark H.,2020-09-09,Walmart,call refund tell would take day get money back,"["" 'price and value'"", "" 'payment and checkout'""]",neutral,0.0
87644,Lorna B.,2021-09-09,Walmart,far too many grocery available store not avail...,"["" 'technology'"", "" 'general'""]",neutral,0.0
87645,NATISHA J.,2021-09-09,Walmart,place need walmart lead sell good merchandise ...,"["" 'shopping experience'""]",positive,0.0

In [24]:
#if the 'data integration' is 1.0, keep it, otherwise, drop it 
df_data = df_data[df_data["'data integration'"] == 1.0]
df_data

KeyError: "'data integration'"